# Generated by Django 2.2.12 on 2020-06-23 22:56

from django.db import migrations, models
import django.db.models.deletion
import libs.mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='文章标题')),
                ('content', models.TextField(max_length=4194304, verbose_name='文章内容')),
            ],
            options={
                'verbose_name': '文章索引',
                'verbose_name_plural': '文章索引',
                'db_table': 't_article_index',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True)),
                ('category', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='二级分类')),
            ],
            options={
                'verbose_name': '文章二级分类表',
                'verbose_name_plural': '文章二级分类表',
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32, verbose_name='标签')),
                ('title', models.CharField(max_length=64, verbose_name='文章title')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
                'db_table': 't_tag',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('first_category', models.CharField(default='程序设计', max_length=32, verbose_name='一级分类')),
                ('tags', models.CharField(max_length=64, verbose_name='文章标签')),
                ('description', models.CharField(max_length=256, verbose_name='简介')),
                ('content', libs.mdeditor.fields.MDTextField(verbose_name='文章正文')),
                ('date', models.DateTimeField(verbose_name='发表日期')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('love_num', models.IntegerField(default=0, verbose_name='点赞量')),
                ('location', models.CharField(default='广东省深圳市', max_length=32, verbose_name='地理位置')),
                ('status', models.IntegerField(default=0, verbose_name='文章状态')),
                ('second_category', models.ForeignKey(default='C++', on_delete=django.db.models.deletion.CASCADE, to='articles.Category', verbose_name='二级分类')),
            ],
            options={
                'verbose_name': '文章表',
                'verbose_name_plural': '文章表',
                'db_table': 't_article',
            },
        ),
    ]
